import { Component, OnInit } from '@angular/core';
import jsPDF from 'jspdf';

@Component({
  selector: 'app-third',
  templateUrl: './third.component.html',
  styleUrls: ['./third.component.css']
})
export class ThirdComponent implements OnInit {

  constructor() { }
  memoType:any='';
  text:string[]=[];
  doc=new jsPDF();
  y:number=20;
  ngOnInit(): void {
    this.text = JSON.parse(localStorage.getItem("memo-data")|| '{}');
    this.memoType=localStorage.getItem("memoType")
    console.log(this.text,'whole data')
    this.updatememo(this.text)
  }

updatememo(text:string[]){
  // var temp=question+"\n\n"+ans+"\n\n"+"\n"
  const now=new Date()
  this.doc.text(`This output has been generated by the tool.It is a draft document, \n
  and is required to be reviewed, completed and modified by \n
  the engagement team and by the Engagement Partner and EQCR (as required by your member firm).\n
  This includes not only review of the specific outstanding matters,\n
  identified by brackets (“< >”), that require clarification or confirmation by the engagement team \n
  before sending it to the client, but also a review of the steps taken within the tool to confirm that the\n
  specific inputs and data points used to generate this result were correct and have also been confirmed.\n
  Member firms leveraging this output in the delivery of services must ensure that the format, \n
  structure, and content is appropriate for the particular engagement, and follows applicable member firm risk review\n
  processes prior to dissemination.`,10,this.y)

  this.y=this.y+150
  var date="Date :"+now.toDateString()
  this.doc.text(date,10,this.y)
  this.y=this.y+15
  var temp ="Accounting and standards : "+this.memoType
  this.doc.text(temp,10,this.y);
  this.y=this.y+15
  this.doc.text("Analysis:",10,this.y);
  this.y=this.y+15
  this.doc.text(text,10,this.y);
  this.y=this.y+20
  }
  downloadMemo(){
    console.log("inside dowload memo")
    this.doc.save("Memo.pdf");
  }
}
